workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Check iOS folder
        script: |
          pwd
          ls -la ios/
          ls -la ios/Runner/
      - name: Initialize iOS project
        script: |
          rm -rf ios
          flutter create --platforms=ios .
          ls -la ios/
      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app