workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app