workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Initialize iOS project
        script: |
          pwd
          ls -la
          flutter create --platforms=ios .
          cd ios && pod install --repo-update && cd ..
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
